### ISSUE TITLE
Argo: Building Model Network

### ISSUE THREAD

**Issue by SLSCHWARTZ1212** [boozallen/argo#24]
I tried running an ARGO simulation using RTA instead of Native Excel.  The file, in the bottom left corner states "Argo: Building Model Network Result - XXXXXXXXXXXXX".  I only ran it for 10 simulations to try it out, and the "Building Model Network Result is now over 2,300,0000 and continues to climb.  Anyone know what is occurring?

**Comment by brandonherzog** [comment]
Hi @SLSCHWARTZ1212, when using RTA mode Argo will attempt to trace backwards from any `RtaResult` cells in order to find all possible input variables which it uses to build an efficient computation graph for the simulation. Unfortunately, as an add-on, the tools available to Argo to do this are less powerful than what is available to Excel itself. Extremely complicated models with huge numbers of input variables can easily get into the millions and take a prohibitively large amount of time to trace--at which point it's usually better to just use Native Excel mode.

However, if your model is small then this isn't expected behavior and it would be great if you could share a sample that reproduces this behavior!

**Comment by SLSCHWARTZ1212** [comment]
@brandonherzog Thanks for the response, this is what I assumed was happening and I did switch to Native Excel, just wasnt sure if it was a larger issue.

Appreciate the response.
